apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-08-26T01:34:14Z"
  generation: 1
  labels:
    app: hello-node
  name: hello-node
  namespace: default
  resourceVersion: "940812"
  selfLink: /apis/apps/v1/namespaces/default/deployments/hello-node
  uid: 5523e221-7a97-4836-8515-02fa886e4db2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-node
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-node
    spec:
      containers:
      - image: k8s.gcr.io/echoserver:1.4
        imagePullPolicy: IfNotPresent
        name: echoserver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-08-26T01:34:12Z"
    lastUpdateTime: "2020-08-26T01:34:12Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-08-26T01:34:00Z"
    lastUpdateTime: "2020-08-26T01:34:12Z"
    message: ReplicaSet "hello-node-7dc7987866" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-08-26T01:35:24Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: hello-node
  name: hello-node
  namespace: default
  resourceVersion: "940912"
  selfLink: /api/v1/namespaces/default/services/hello-node
  uid: 93815864-6e7e-4283-ae06-6a792eb61ded
spec:
  clusterIP: 10.0.216.76
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30696
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-node
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 191.234.221.66